theme: jekyll-theme-slate
title: Season Studio
description: Technology base on the human race
show_downloads: false
github:
    is_project_page: true
    repository_url: https://github.com/season-studio/
    owner_name: Season Studio
    owner_url: https://season-studio.github.io/
