theme: jekyll-theme-slate
title: Season Studio
description: Technology is people-oriented
show_downloads: false
github:
    is_project_page: true
    repository_url: https://github.com/season-studio/
    owner_name: Season
    owner_url: mailto:season-studio@outlook.com
